package kristenores.mod.init;

import java.util.ArrayList;
import java.util.List;

import kristenores.mod.objects.items.ItemBase;
import net.minecraft.item.Item;

public class ItemInit {
	public static final List<Item> ITEMS = new ArrayList<Item>();
	
	public static final Item INGOT_COPPER1 = new ItemBase("ingot_copper1");
	public static final Item INGOT_COPPER2 = new ItemBase("ingot_copper2");
	public static final Item INGOT_COPPER3 = new ItemBase("ingot_copper3");
	public static final Item INGOT_COPPER4 = new ItemBase("ingot_copper4");
	public static final Item INGOT_COPPER5 = new ItemBase("ingot_copper5");
	public static final Item INGOT_COPPER6 = new ItemBase("ingot_copper6");
	public static final Item INGOT_COPPER7 = new ItemBase("ingot_copper7");
	public static final Item INGOT_COPPER8 = new ItemBase("ingot_copper8");
	public static final Item INGOT_COPPER9 = new ItemBase("ingot_copper9");
	public static final Item INGOT_COPPER10 = new ItemBase("ingot_copper10");
	public static final Item INGOT_COPPER11 = new ItemBase("ingot_copper11");
	public static final Item INGOT_COPPER12 = new ItemBase("ingot_copper12");
	public static final Item INGOT_COPPER13 = new ItemBase("ingot_copper13");
	public static final Item INGOT_COPPER14 = new ItemBase("ingot_copper14");
	public static final Item INGOT_COPPER15 = new ItemBase("ingot_copper15");
	public static final Item INGOT_COPPER16 = new ItemBase("ingot_copper16");
	public static final Item INGOT_COPPER17 = new ItemBase("ingot_copper17");
	public static final Item INGOT_COPPER18 = new ItemBase("ingot_copper18");
	public static final Item INGOT_COPPER19 = new ItemBase("ingot_copper19");
	public static final Item INGOT_COPPER20 = new ItemBase("ingot_copper20");
	public static final Item INGOT_COPPER21 = new ItemBase("ingot_copper21");
	public static final Item INGOT_COPPER22 = new ItemBase("ingot_copper22");
	public static final Item INGOT_COPPER23 = new ItemBase("ingot_copper23");
	public static final Item INGOT_COPPER24 = new ItemBase("ingot_copper24");
	public static final Item INGOT_COPPER25 = new ItemBase("ingot_copper25");
	public static final Item INGOT_COPPER26 = new ItemBase("ingot_copper26");
	public static final Item INGOT_COPPER27 = new ItemBase("ingot_copper27");
	public static final Item INGOT_COPPER28 = new ItemBase("ingot_copper28");
	public static final Item INGOT_COPPER29 = new ItemBase("ingot_copper29");
	public static final Item INGOT_COPPER30 = new ItemBase("ingot_copper30");
	public static final Item INGOT_COPPER31 = new ItemBase("ingot_copper31");
	public static final Item INGOT_COPPER32 = new ItemBase("ingot_copper32");
	public static final Item INGOT_COPPER33 = new ItemBase("ingot_copper33");
	public static final Item INGOT_COPPER34 = new ItemBase("ingot_copper34");
	public static final Item INGOT_COPPER35 = new ItemBase("ingot_copper35");
	public static final Item INGOT_COPPER36 = new ItemBase("ingot_copper36");
	public static final Item INGOT_COPPER37 = new ItemBase("ingot_copper37");
	public static final Item INGOT_COPPER38 = new ItemBase("ingot_copper38");
	public static final Item INGOT_COPPER39 = new ItemBase("ingot_copper39");
	public static final Item INGOT_COPPER40 = new ItemBase("ingot_copper40");
	public static final Item INGOT_COPPER41 = new ItemBase("ingot_copper41");
	public static final Item INGOT_COPPER42 = new ItemBase("ingot_copper42");
	public static final Item INGOT_COPPER43 = new ItemBase("ingot_copper43");
	public static final Item INGOT_COPPER44 = new ItemBase("ingot_copper44");
	public static final Item INGOT_COPPER45 = new ItemBase("ingot_copper45");
	public static final Item INGOT_COPPER46 = new ItemBase("ingot_copper46");
	public static final Item INGOT_COPPER47 = new ItemBase("ingot_copper47");
	public static final Item INGOT_COPPER48 = new ItemBase("ingot_copper48");
	public static final Item INGOT_COPPER49 = new ItemBase("ingot_copper49");
	public static final Item INGOT_COPPER50 = new ItemBase("ingot_copper50");
	public static final Item INGOT_COPPER51 = new ItemBase("ingot_copper51");
	public static final Item INGOT_COPPER52 = new ItemBase("ingot_copper52");
	public static final Item INGOT_COPPER53 = new ItemBase("ingot_copper53");
	public static final Item INGOT_COPPER54 = new ItemBase("ingot_copper54");
	public static final Item INGOT_COPPER55 = new ItemBase("ingot_copper55");
	public static final Item INGOT_COPPER56 = new ItemBase("ingot_copper56");
	public static final Item INGOT_COPPER57 = new ItemBase("ingot_copper57");
	public static final Item INGOT_COPPER58 = new ItemBase("ingot_copper58");
	public static final Item INGOT_COPPER59 = new ItemBase("ingot_copper59");
	public static final Item INGOT_COPPER60 = new ItemBase("ingot_copper60");
	public static final Item INGOT_COPPER61 = new ItemBase("ingot_copper61");
	public static final Item INGOT_COPPER62 = new ItemBase("ingot_copper62");
	public static final Item INGOT_COPPER63 = new ItemBase("ingot_copper63");
	public static final Item INGOT_COPPER64 = new ItemBase("ingot_copper64");
	public static final Item INGOT_COPPER65 = new ItemBase("ingot_copper65");
	public static final Item INGOT_COPPER66 = new ItemBase("ingot_copper66");
	public static final Item INGOT_COPPER67 = new ItemBase("ingot_copper67");
	public static final Item INGOT_COPPER68 = new ItemBase("ingot_copper68");
	public static final Item INGOT_COPPER69 = new ItemBase("ingot_copper69");
	public static final Item INGOT_COPPER70 = new ItemBase("ingot_copper70");
	public static final Item INGOT_COPPER71 = new ItemBase("ingot_copper71");
	public static final Item INGOT_COPPER72 = new ItemBase("ingot_copper72");
	public static final Item INGOT_COPPER73 = new ItemBase("ingot_copper73");
	public static final Item INGOT_COPPER74 = new ItemBase("ingot_copper74");
	public static final Item INGOT_COPPER75 = new ItemBase("ingot_copper75");
	public static final Item INGOT_COPPER76 = new ItemBase("ingot_copper76");
	public static final Item INGOT_COPPER77 = new ItemBase("ingot_copper77");
	public static final Item INGOT_COPPER78 = new ItemBase("ingot_copper78");
	public static final Item INGOT_COPPER79 = new ItemBase("ingot_copper79");
	public static final Item INGOT_COPPER80 = new ItemBase("ingot_copper80");
	public static final Item INGOT_COPPER81 = new ItemBase("ingot_copper81");
	public static final Item INGOT_COPPER82 = new ItemBase("ingot_copper82");
	public static final Item INGOT_COPPER83 = new ItemBase("ingot_copper83");
	public static final Item INGOT_COPPER84 = new ItemBase("ingot_copper84");
	public static final Item INGOT_COPPER85 = new ItemBase("ingot_copper85");
	public static final Item INGOT_COPPER86 = new ItemBase("ingot_copper86");
	public static final Item INGOT_COPPER87 = new ItemBase("ingot_copper87");
	public static final Item INGOT_COPPER88 = new ItemBase("ingot_copper88");
	public static final Item INGOT_COPPER89 = new ItemBase("ingot_copper89");
	public static final Item INGOT_COPPER90 = new ItemBase("ingot_copper90");
	public static final Item INGOT_COPPER91 = new ItemBase("ingot_copper91");
	public static final Item INGOT_COPPER92 = new ItemBase("ingot_copper92");
	public static final Item INGOT_COPPER93 = new ItemBase("ingot_copper93");
	public static final Item INGOT_COPPER94 = new ItemBase("ingot_copper94");
	public static final Item INGOT_COPPER95 = new ItemBase("ingot_copper95");
	public static final Item INGOT_COPPER96 = new ItemBase("ingot_copper96");
	public static final Item INGOT_COPPER97 = new ItemBase("ingot_copper97");
	public static final Item INGOT_COPPER98 = new ItemBase("ingot_copper98");
	public static final Item INGOT_COPPER99 = new ItemBase("ingot_copper99");
	public static final Item INGOT_COPPER100 = new ItemBase("ingot_copper100");
	public static final Item INGOT_COPPER101 = new ItemBase("ingot_copper101");
	public static final Item INGOT_COPPER102 = new ItemBase("ingot_copper102");

}
